# Generated by Django 2.2 on 2019-05-02 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_album_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='likes',
        ),
    ]
